import test from 'node:test';
import assert from 'node:assert/strict';
import {createSystems,takeImpact,tickSystems,activateSystem,attractCoin} from '../www/rocket-systems.js';
import {ProgressStore,RewardedAds} from '../www/progression.js';
const memory=(seed={})=>{const m=new Map(Object.entries(seed));return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};};
test('Scout is fragile; Ranger survives precisely one light scrape, never a major impact',()=>{assert.equal(takeImpact(createSystems(),2),'fatal');const r=createSystems('ranger');assert.equal(takeImpact(r,3),'damaged');assert.equal(r.damage,1);tickSystems(r,1);assert.equal(takeImpact(r,2),'fatal');assert.equal(takeImpact(createSystems('ranger'),2,true),'fatal');});
test('legacy coins, selected rockets and separate records survive migration and reload',()=>{const s=memory({wilifunkCoins:'730',wilifunkUnlockedRockets:'["pioneer","red_fury"]',wilifunkSelectedRocket:'red_fury',spacerootRecords:'[{"score":17,"distance":3200}]',spacehullTapBestScore:'43'});const p=new ProgressStore(s);assert.equal(p.data.coins,730);assert.equal(p.data.equippedRocket,'red_fury');assert.equal(p.data.exploreBestDistance,3200);assert.equal(p.data.tapBestScore,43);assert.equal(new ProgressStore(s).data.coins,730);});
test('milestones and purchases are idempotent and respect gates',()=>{const p=new ProgressStore(memory());p.advance('explore',500);p.advance('explore',500);assert.equal(p.data.coins,100);p.data.coins=50000;assert.equal(p.purchase('voyager'),false);p.data.exploreBestDistance=15000;assert.equal(p.purchase('voyager'),true);assert.equal(p.data.coins,32000);assert.equal(p.purchase('voyager'),false);p.advance('tap',10);assert.equal(p.data.coins,32100);});
test('mission claims are period-bound and cannot pay twice',()=>{const p=new ProgressStore(memory(),()=>100000000);p.metric('near',5);assert(p.claimMission('near'));assert(!p.claimMission('near'));assert.equal(p.data.coins,100);});
test('magnet curves only coins; phase is manual and once per run',()=>{const s=createSystems('magnetar'),coin={type:'coin',x:50,y:0},star={type:'star',x:50,y:0};attractCoin(coin,{x:0,y:0},s,.1);attractCoin(star,{x:0,y:0},s,.1);assert(coin.x<50);assert.equal(star.x,50);const p=createSystems('phantom');assert.equal(p.phase,0);assert(activateSystem(p));assert.equal(takeImpact(p,100,true),'protected');tickSystems(p,2);assert(!activateSystem(p));});
test('rewarded ads fail closed without a provider and grant once after a verified callback',async()=>{assert.equal(await new RewardedAds().request('a','rescue'),false);const a=new RewardedAds({showRewarded:async()=>true});assert(await a.request('run-a','double'));assert.equal(await a.request('run-a','double'),false);});
test('Phantom and Odyssey unlock by distance without scanning',()=>{const p=new ProgressStore(memory());p.data.coins=100000;assert.equal(p.purchase('phantom'),false);p.data.exploreBestDistance=35000;assert(p.purchase('phantom'));assert.equal(p.purchase('odyssey'),false);p.data.exploreBestDistance=50000;assert(p.purchase('odyssey'));assert.equal(p.data.discoveries.length,0);});
test('valid backup recovers a damaged primary save without resetting coins',()=>{const storage=memory();const p=new ProgressStore(storage);p.data.coins=777;p.commit();storage.setItem('spacehullProfileBackup',JSON.stringify(p.data));storage.setItem('spacehullProfile','{broken');const recovered=new ProgressStore(storage);assert.equal(recovered.data.coins,777);assert.equal(new ProgressStore(storage).data.coins,777);});
test('legacy global paint migrates once onto its equipped rocket and survives reload',()=>{
 const storage=memory({spacehullProfile:JSON.stringify({equippedRocket:'ranger',ownedRockets:['pioneer','ranger'],equippedPaint:'arctic',cosmetics:['arctic']})});
 const p=new ProgressStore(storage);assert.equal(p.data.rocketPaints.ranger,'arctic');assert.equal(p.data.rocketPaints.pioneer,undefined);
 p.data.equippedRocket='pioneer';p.commit();const reloaded=new ProgressStore(storage);assert.equal(reloaded.data.rocketPaints.pioneer,undefined);assert.equal(reloaded.data.rocketPaints.ranger,'arctic');
 reloaded.cosmetic('arctic');assert.equal(reloaded.data.rocketPaints.pioneer,'arctic');
});
