import test from 'node:test';import assert from 'node:assert/strict';import {ProgressStore} from '../www/progression.js';
const memory=()=>{const d=new Map();return {getItem:k=>d.get(k)??null,setItem:(k,v)=>d.set(k,v)};};
function attempt(p,score,status='over'){p.startSalvage();const id=p.data.salvageRun.id;const state=p.data.salvageRun.puzzle;state.score=score;state.status=status;p.saveSalvage(state,id);return id;}
test('Salvage charges persist across reload and resume never spends twice',()=>{const storage=memory(),p=new ProgressStore(storage);assert.equal(p.data.salvageCharges,2);p.startSalvage();const id=p.data.salvageRun.id;assert.equal(p.data.salvageCharges,1);const q=new ProgressStore(storage);q.startSalvage();assert.equal(q.data.salvageCharges,1);assert.equal(q.data.salvageRun.id,id);assert(q.restartSalvage());q.startSalvage();assert.equal(q.data.salvageCharges,0);assert.equal(q.restartSalvage(),false);});
test('Salvage target claim and first achievement pay once, even in stale tabs',()=>{const storage=memory(),p=new ProgressStore(storage);const id=attempt(p,2500,'playing');const q=new ProgressStore(storage);assert(p.claimSalvage(id));assert.equal(p.data.coins,400);assert.equal(p.data.salvageSuccessfulRuns,1);assert.equal(q.claimSalvage(id),false);assert.equal(q.data.coins,400);assert.equal(p.saveSalvage(p.data.salvageRun.puzzle,id),false);});
test('Salvage overtime caps coins, grants one component and doubles only run coins',()=>{const p=new ProgressStore(memory());const id=attempt(p,1000000);assert(p.claimSalvage(id));assert.equal(p.data.coins,500);assert.equal(p.data.components.length,1);assert(p.doubleSalvage(id));assert.equal(p.data.coins,900);assert.equal(p.data.components.length,1);assert.equal(p.doubleSalvage(id),false);assert.equal(p.data.salvageMilestones.length,1);});
test('Salvage failure cannot claim while playing, rewards capped on failure',()=>{const p=new ProgressStore(memory());const id=attempt(p,1240,'playing');assert.equal(p.claimSalvage(id),false);p.data.salvageRun.puzzle.status='over';p.saveSalvage(p.data.salvageRun.puzzle,id);assert(p.claimSalvage(id));assert.equal(p.data.coins,62);assert.equal(p.data.salvageSuccessfulRuns,0);assert.equal(p.doubleSalvage(id),false);});
test('Salvage recovery is once per attempt and replaces the unusable tray',()=>{const p=new ProgressStore(memory());const id=attempt(p,500);const r=p.data.salvageRun;r.puzzle.board=Array(64).fill(1);r.puzzle.board[0]=0;r.puzzle.tray=[{shape:8,material:1}];p.saveSalvage(r.puzzle,id);assert(p.recoverSalvage(id));assert.equal(p.data.salvageRun.puzzle.status,'playing');assert.equal(p.recoverSalvage(id),false);});
test('Flight milestones grant capped charges once and retain shared wallet',()=>{const p=new ProgressStore(memory());p.data.salvageCharges=0;p.commit();p.advance('explore',500);assert.equal(p.data.salvageCharges,1);assert.equal(p.data.coins,100);p.advance('explore',500);assert.equal(p.data.salvageCharges,1);p.advance('tap',100);assert.equal(p.data.salvageCharges,3);});
test('Storage failure rolls back consumed charge',()=>{const storage=memory(),p=new ProgressStore(storage);storage.setItem=()=>{throw Error('full');};assert.equal(p.startSalvage(),false);assert.equal(p.data.salvageCharges,2);assert.equal(p.data.salvageRun,null);});

test('Salvage fifty-success progression grants each milestone and cosmetic once',()=>{const p=new ProgressStore(memory());for(let i=0;i<51;i++){p.data.salvageCharges=1;p.commit();const id=attempt(p,2500);assert(p.claimSalvage(id));}assert.deepEqual(p.data.salvageMilestones,[1,5,10,20,30,50]);assert.equal(p.data.coins,51*300+600);assert.deepEqual(p.data.salvageCosmeticsEarned,['ion','arctic','salvage-veteran']);assert.equal(p.data.components.filter(c=>c==='phase_module').length,1);});
