import test from 'node:test';import assert from 'node:assert/strict';import {SalvagePuzzle,SHAPES,valid,clearLines,placements} from '../www/salvage.js';
test('Salvage rejects overlap and every out-of-bounds edge without mutation',()=>{const p=new SalvagePuzzle();p.tray=[{shape:8,material:2}];p.board[0]=1;const before=JSON.stringify(p.snapshot());for(const [x,y] of [[0,0],[-1,0],[7,7],[0,-1],[8,0]])assert.equal(p.place(0,x,y),null);assert.equal(JSON.stringify(p.snapshot()),before);});
test('Salvage simultaneously clears a row and column once',()=>{const p=new SalvagePuzzle();p.board=Array(64).fill(0);for(let i=1;i<8;i++){p.board[i]=1;p.board[i*8]=1;}p.tray=[{shape:0,material:3},{shape:8,material:1}];const r=p.place(0,0,0);assert.equal(r.lines,2);assert.equal(r.cells.length,15);assert.equal(p.score,255);assert(p.board.every(v=>!v));});
test('Salvage three rows and four columns clear correctly',()=>{for(const n of [3,4]){const b=Array(64).fill(0);for(let y=0;y<8;y++)for(let x=0;x<8;x++)if(n===3?y<3:x<4)b[y*8+x]=1;assert.equal(clearLines(b).lines,n);assert(b.every(v=>!v));}});
test('Salvage replenishes only after all three pieces, supports any order',()=>{const p=new SalvagePuzzle(()=>0);p.tray=Array.from({length:3},()=>({shape:0,material:1}));p.place(2,0,0);assert.equal(p.tray[2],null);p.place(0,1,0);assert.equal(p.tray[1].shape,0);p.place(1,2,0);assert.equal(p.tray.filter(Boolean).length,3);});
test('Salvage game over checks all available shapes',()=>{const p=new SalvagePuzzle();p.board=Array(64).fill(1);p.board[0]=0;p.tray=[{shape:8,material:1},{shape:0,material:1}];assert.equal(p.check(),'playing');p.tray[1]=null;assert.equal(p.check(),'over');});
test('Salvage weighted batches admit a legal placement sequence',()=>{let seed=42;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);function solve(board,tray){if(!tray.length)return true;return tray.some((p,i)=>placements(board,SHAPES[p.shape]).some(([x,y])=>{const b=[...board];for(const [dx,dy] of SHAPES[p.shape])b[(y+dy)*8+x+dx]=1;clearLines(b);return solve(b,tray.filter((_,j)=>i!==j));}));}for(let k=0;k<35;k++){const p=new SalvagePuzzle(random);p.board=p.board.map(()=>random()<.45?1:0);clearLines(p.board);p.generate();assert.equal(p.tray.length,3);assert(solve(p.board,p.tray));}});
test('Salvage chains tolerate two misses and expire on the third; saves resume exactly',()=>{const p=new SalvagePuzzle();p.chain=3;p.tray=Array.from({length:3},()=>({shape:0,material:1}));p.place(0,0,0);p.place(1,1,0);assert.equal(p.chain,3);p.place(2,2,0);assert.equal(p.chain,0);assert.deepEqual(new SalvagePuzzle(Math.random,p.snapshot()).snapshot(),p.snapshot());});

test('Salvage long simulated games never overlap, corrupt the board or repeat cleared lines',()=>{let seed=301;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);for(let run=0;run<25;run++){const p=new SalvagePuzzle(random);for(let move=0;move<150&&p.status==='playing';move++){const choices=p.tray.flatMap((piece,slot)=>piece?placements(p.board,SHAPES[piece.shape]).map(([x,y])=>({slot,x,y})):[]);assert(choices.length);const c=choices[Math.floor(random()*choices.length)],before=p.score;assert(p.place(c.slot,c.x,c.y));assert(p.score>before);assert.equal(p.board.length,64);assert(p.board.every(n=>Number.isInteger(n)&&n>=0&&n<=5));assert.equal(clearLines([...p.board]).lines,0);}}});
